from . import help
from . import start
from . import order
from . import texts
from . import admin
from . import shartlar
from . import branches
from . import aloqa
from . import faq
from . import language
